### ISSUE TITLE
Support for stepper driven extruders

### ISSUE THREAD

**Issue by Lenbok** [makerbot/G3Firmware#48]
It was possible to compile the 1.8 firmware to support stepper driven extruders, either directly from the extruder board, or (with Rick Pollack's patch) via a separate stepper driver. 

More people are becoming interested in a stepper driven extruder as an option, so it would be good to have support for this in the latest firmware. (There was mention at the initial release of 2.0 firmware about plans to support this, but I haven't seen anything since, and there are no current issues that seem to track this).

**Comment by phooky** [comment]
Hi,

There's now (finally) a build of the v2.3 software that supports this!  Sorry for the long wait.

See http://wiki.makerbot.com/stepper-driven-extruder#version-2 for details.

-a

**Comment by Lenbok** [comment]
Fantastic, I can't wait to try this out!

**Comment by tbuser** [comment]
Thanks!

**Comment by Lenbok** [comment]
OK, I had a chance to try this out just now.

I enabled experimental firmware and saw there were two stepper enabled firmwares available. I selected the most recent and uploaded it.

In repg I had the regular cupcake driver selected and opened the control panel. I first entered 10 into the PWM box and hit forward. The stepper made some jerky movements, but nothing reliable. I then put 100 into the box and tried that. More movements, but still nothing reliably forward. I felt the H-bridges and they were _very_ hot, so I immediately shut the bot down.

I re-uploaded my 1.8 stepper-enabled firmware, flicked the repg driver back to my one with the old stepper tool enabled, and entered my usual PWM of 140 and RPM of 10. The motor still moves fine (so I haven't cooked my H-bridges :-)). With the old firmware having the PWM up too high makes the h-bridges get hot and movement is unreliable - perhaps the new firmware is trying to drive them too hard?

I am using Lin Engineering 4218L-01-10 from Alltronics, if that matters.

**Comment by Atntias** [comment]
Hi, i olso tryed the beta fimware and have exactly same resualts as described by Lenbok, no reliable movent genereted..

**Comment by phooky** [comment]
Sorry, the r4 version is buggy.  Try the r3 version, which is still in the firmware list.  I'm going to upload another version soon, but these are somewhat stopgappy until I get onboard configuration support in there.  Working on a lot of things at the same time.  :)

**Comment by Lenbok** [comment]
Will the r3 be less likely to overheat the h-bridges? Is there an equivalent to the PWM limiting that you can do in the 1.8 versions?

**Comment by Atntias** [comment]
well tried r3 but isn't any better it doesn't move the stepper continuously in one direction, in 1.8 it is pretty much working i wish there was support in 2.3 to use stepper both from the onboard and from pololu stepper driver, in 1.8 theres a patched firmware that dose that too. 
also im only using the firmware distrusted by repG to test it only that because its unusable for me as my thermosister pin (3) has died, and i had to use pin 7, and threes no way to change that in the settings(i opened an issue on that), so i stick to the 1.8 version where i understand how to compile becuse the 2.3 version i tried for hours to compile and didn't understand how to do that.
